package com.example.demo.Services;

import java.util.ArrayList;
//import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Component;

import com.example.demo.Beans.User;
import com.example.demo.Repository.UserRepository;

@Component
public class UserDaoService {
	
	@Autowired
	UserRepository userRepository;

//	private static List<User> users=new ArrayList<User>();
//	int userCount=3;//this value is generated by db as forgien key in real time
//	
//	static {
//		users.add(new User(,"Vikky1","Admin1"));
//		users.add(new User(2,"Vikky2","Admin2"));
//		users.add(new User(3,"Vikky3","Admin3"));
//	}
//	
	//type of operations we do with this is Service is
	//method to findAll,findOne,save
	
	public List<User> findAll(){
		return userRepository.findAll();
	}
	
	public Optional<User> findById(Long id){
		return userRepository.findById(id);
	}
}
